### ISSUE TITLE
undefined method `in_columns'

### ISSUE THREAD

**Issue by infominer33** [planet-templates/planet-top#1]
I have got my first page built via the pluto.starter repository, but I can't seem to get this theme to work.

I've tried a few variants of `pluto b planet.ini -t top -o build` but they always end in:

```
*** error: undefined method `in_columns' for #<Pluto::Model::Feed::ActiveRecord_AssociationRelation:0x00007ffe2e35a820>
```

it seems this is the offending line from top.html.erb:

```
<%  site.feeds.latest.in_columns(3).each do |feeds| %>
```

Tho I've no clue how to resolve it.

Thank you!

**Comment by geraldb** [comment]
Thanks for trying pluto and reporting the error. That's an easy fix. Sorry for the trouble that's an ActiveRecord upgrade issue => Convert items to array before applying in_columns
change:

    site.feeds.latest.in_columns(3)

to

    site.feeds.latest.to_a.in_columns(3)

Note: The missing / new  `to_a`.  Now it should work "as advertised".  I updated / fixed the template itself. Cheers.

**Comment by geraldb** [comment]
I assume it's working now.  If not, please report back (and I reopen the issue). Good luck. Cheers.

**Comment by infominer33** [comment]
Heyyy! Thanks so much!!

For the fast response and all the fun with pluto:

* [planet.starter](https://infominer.id/feed-test/planet.starter.html)
* [blank](https://infominer.id/feed-test/planet.html)
  * [planet.cards](https://infominer.id/feed-test/planet.cards.html)
* [planet.top](https://infominer.id/feed-test/planet.top.html)

Right now I'm using rsshub  for the feeds... I'd love to figure how to generate something like the [Unvanquished Activity](https://unvanquished.net/activity/) where I can follow the thread, not just the topics, tho... 

just throwing it out there in case you can point me in the right direction..

**Comment by geraldb** [comment]
Thanks for the update. The mailing list / forum @ <http://groups.google.com/group/wwwmake> is the best / recommended channel for discussion.   As far as I can remember the setup for Unvanquished Activity is open source, see <https://github.com/Unvanquished/pluto-devfeeds> for how it's all put together including all templates.
